# Generated by Django 5.2.6 on 2025-11-13 05:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0010_alter_cliente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionVentas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prediccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('venta_predicha', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('confianza', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Predicción de Venta',
                'verbose_name_plural': 'Predicciones de Ventas',
                'ordering': ['-fecha_prediccion', 'categoria', 'periodo_inicio'],
            },
        ),
    ]
